$('.owl-carousel').owlCarousel({
    loop:false,
    margin:10,
    nav:false,
    responsive:{
        0:{
            items:1
        },
        600:{
            items:3
        },
        700:{
            items:4
        },
        800:{
            items:5
        },
        1000:{
            items:6
        }
    }
})